// const {clearCodeAdapter} = require('../persistance/module')
// ...

// const deleteDataUseCase = new DeleteDataService(clearCodeAdapter, ...);
// ...

// const deleteController = new deleteController(deleteDataUseCase);
// const ...
